name: Main workflow for Food Orderring System

on:
  push:
    branches:
      - main
      - dev
      - 'FT/*'
      - 'UI/*'
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  terraform:
    needs: build
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/change_mangment.yaml
